export * from './auth.validator';
export * from './patient.validator';
export * from './doctor.validator';
export * from './medicalRecord.validator';
export * from './prescription.validator';
export * from './attachment.validator';
export * from './statistics.validator';
export * from './department.validator';
export * from './system.validator';
